version: "3.8"

volumes:
  db-data:
    name: reminder-bot-db

services:
  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./config.ini:/src/config.ini
    depends_on:
      - "db"

  db:
    image: mariadb:10.5.4
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: reminders
      MYSQL_USER: reminderbot
      MYSQL_PASSWORD_FILE: '/run/secrets/mysql-password'
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db-password:/run/secrets/mysql-password
        #- ./create.sql:/docker-entrypoint-initdb.d/01-create.sql
