version: "3.8"

volumes:
  db-data:
    name: reminder-bot-db

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: unless-stopped
    volumes:
      - ./config.ini:/src/config.ini
    depends_on:
      - "db"

  postman:
    build:
      context: .
      dockerfile: ./docker/postman/Dockerfile
    restart: unless-stopped
    volumes:
      - ./postman-rs/.env:/app/.env
    depends_on:
      - "db"

  db:
    image: linuxserver/mariadb
    environment:
      FILE__MYSQL_ROOT_PASSWORD: '/run/secrets/mysql-password'
      MYSQL_DATABASE: reminders
      MYSQL_USER: reminderbot
      FILE__MYSQL_PASSWORD: '/run/secrets/mysql-password'
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db-password:/run/secrets/mysql-password
