version: "3.8"

volumes:
  db-data:
    name: reminder-bot-db

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: unless-stopped
    volumes:
      - ./config.ini:/src/config.ini:ro
    depends_on:
      - "db"

  postman:
    build:
      context: .
      dockerfile: ./docker/postman/Dockerfile
    restart: unless-stopped
    volumes:
      - ./postman-rs/.env:/app/.env:ro
    depends_on:
      - "db"

  db:
    image: biarms/mysql:5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: reminders
      MYSQL_USER: reminderbot
      MYSQL_PASSWORD_FILE: '/run/secrets/mysql-password'
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db-password:/run/secrets/mysql-password:ro
